---

- name: "SCORED | 2.2.36 | POLICY | L2 Ensure Log on as a batch job is set to Administrators DC Only"
  win_user_right:
    name: SeBatchLogonRight
    users: Administrators
    action: set
  when: cis[2019]['2_2_36
    - ansible_windows_domain_role == "Primary domain controller"
  tags:
    - level2-domaincontroller
    - control_2.2.36

- name: "SCORED | 2.3.7.6 | POLICY | L2 Ensure Interactive logon Number of previous logons to cache in case domain controller is not available is set to 4 or fewer logons MS only"
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon
    name: cachedlogonscount
    data: 1
    type: string
  when: cis[2019]['2_3_7_6']
  tags:
    - level2-memberserver
    - control_2.3.7.6

    - name: "SCORED | 2.3.10.4 | POLICY | L2 Ensure Network access Do not allow storage of passwords and credentials for network authentication is set to Enabled"
  win_regedit:
    path: HKLM:\System\Currentcontrolset\Control\Lsa
    name: DisableDomainCreds
    data: 1
    type: dword
  when: cis[2019]['2_3_10_4']
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - control_2.3.10.4


