---

# Section 1

- name: "SCORED | 1.1.1 | POLICY | L1 Ensure Enforce password history is set to 24 or more passwords"
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: "{{ passwordhistorysize }}"
  when: cis[2019]['1.1.1']
  tags:
    - domaincontroller
    - memberserver
    - control_1.1.1

- name: "SCORED | 1.1.2 | POLICY | L1 Ensure Maximum password age is set to 60 or fewer days but not 0"
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: "{{ maximumpasswordage }}"
  when: cis[2019]['1.1.2']
  tags:
    - domaincontroller
    - memberserver
    - control_1.1.2

- name: "SCORED | 1.1.3 | POLICY | L1 Ensure Minimum password age is set to 1 or more days"
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge
    value: "{{ minimumpasswordage }}"
  when: cis[2019]['1.1.3']
  tags:
    - domaincontroller
    - memberserver
    - control_1.1.3

- name: "SCORED | 1.1.4 | POLICY | L1 Ensure Minimum password length is set to 14 or more characters"
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: "{{ minimumpasswordlength }}"
  when: cis[2019]['1.1.4']
  tags:
    - domaincontroller
    - memberserver
    - control_1.1.4

- name: "SCORED | 1.1.5 | POLICY | L1 Ensure Password must meet complexity requirements is set to Enabled"
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 1
  when: cis[2019]['1.1.5']
  tags:
    - domaincontroller
    - memberserver
    - control_1.1.5

- name: "SCORED | 1.1.6 | POLICY | L1 Ensure Store passwords using reversible encryption is set to Disabled"
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: "0"
  when: cis[2019]['1.1.6']
  tags:
    - domaincontroller
    - memberserver
    - control_1.1.6

- name: "SCORED | 1.2.1 | POLICY | L1 Ensure Account lockout duration is set to 15 or more minutes"
  win_security_policy:
    section: System Access
    key: LockoutDuration
    value: "{{ lockoutduration }}"
  when:
    - cis[2019]['1.2.1']
    - is_implemented
  tags:
    - domaincontroller
    - memberserver
    - control_1.2.1

# This rule must be applied first to make control_1.2.1 and control_1.2.3 applicable
- name: "SCORED | 1.2.2 | PATCH | L1 Ensure Account lockout threshold is set to 10 or fewer invalid logon attempts but not 0"
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: "{{ lockoutbadcount }}"
  when: cis[2019]['1.2.2']
  tags:
    - domaincontroller
    - memberserver
    - control_1.2.2

- name: "SCORED | 1.2.3 | PATCH | L1 Ensure Reset account lockout counter after is set to 15 or more minutes"
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: "{{ resetlockoutcount }}"
  when: cis[2019]['1.2.3']
  tags:
    - domaincontroller
    - memberserver
    - control_1.2.3