---

- name: "SCORED | 1.1.1 | POLICY | L1 Ensure Enforce password history is set to 24 or more passwords"
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: "{{ passwordhistorysize }}"
  when: cis[2019]['1_1_1']
  tags:
      - domaincontroller
      - memberserver
      - control_1.1.1