---

- hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Gather distribution info
      setup:
        gather_subset: distribution,!all,!min
      when:
        - ansible_distribution is not defined
      tags: [ 'always' ]

    - name: Check osversion and family
      assert:
        that:
          - ansible_os_family == 'Windows'
          - ansible_distribution | regex_search('Microsoft Windows Server (2016|2019)')
        success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
        fail_msg: "This role can only be run against Windows Server (2016|2019) Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
      tags: [ 'always' ]

    - name: Check ansible version
      assert:
        that: ansible_version.full is version_compare(min_ansible_version, '>=')
        msg: You must use Ansible {{ min_ansible_version }} or greater
      tags: [ 'always' ]

    - name: Include required facts
      include_tasks:
        file: facts.yml
      tags: [ 'always' ]
  
  roles:
    - cis_benchmark
    - nist_benchmark