---

- name: Set system facts based on gather facts module
  block:
      - name: Set fact if system is standalone
        set_fact:
            server_role: "standalone"
        when:
            - ansible_windows_domain_role ==  'Stand-alone server'

      - name: Set fact if domain controller role
        set_fact:
            server_role: "dc"
        when:
            - ansible_windows_domain_role | regex_search('(domain controller)')

      - name: set fact if domain member server
        set_fact:
            server_role: "member"
        when: 
            - ansible_windows_domain_role == 'Member server'

- name: Get Windows installation type
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    name: InstallationType
  register: get_windows_installation_type

- name: Set Windows installation type
  set_fact:
    windows_installation_type: "{{ get_windows_installation_type.value | default('') }}"

- name: Set Windows version
  set_fact:
    os_version: "{{ ansible_distribution | regex_search('Windows Server (2016|2019)') }}"