---

# Import CIS Tests
- name: Import CIS Tests
  include_tasks: 
    file: {{ os_version }}/asserts.yml
  run_once: yes

# Apply CIS Policies
- name: Apply CIS Level 1 Policies
  include_tasks:
    file: {{ os_version }}/Level1.yml

# Apply CIS Policies
- name: Apply CIS Level 2 Policies
  include_tasks:
    file: {{ os_version }}/Level2.yml