---

- debug:
    msg: |
      {{ r2019 | dict2items }}


- tasks:
    - name: {{ item.key }}
      debug:
        msg: Testing loop {{ item }}
      loop: "{{ r2019 | dict2items | selectattr('value.section','eq','System Access') | list }}"

    - name: "Apply User Rights"
      debug:
        msg: Testing loop {{ item }}
      loop: "{{ r2019 | dict2items | selectattr('value.section','eq','User Right') | list }}"