---

# Apply all security policies relating to server role
- name: "Apply Security Policies" 
  win_security_policy:
    section: 'System Access'
    key: "{{ item.value.properties.key }}"
    value: "{{ item.value.properties.value }}"
  when:
    - item.value.enabled
    - server_role == item.value.role
  tags: item.value.tags
  loop: "{{ r2019 | dict2items | selectattr('value.module','eq','System Access') | list }}"
  loop_control:
    label: "{{ item.value.name }}"
    index_var: my_idx

# Apply all user rights relating to server role
- name: "Apply User Rights" 
  win_user_right:
    name: "{{ item.value.properties.name }}"
    users: "{{ item.value.properties.users }}"
    action: "{{ item.value.properties.action }}"
  when:
    - item.value.enabled
    - server_role == item.value.role
  tags: item.value.tags
  loop: "{{ r2019 | dict2items | selectattr('value.module','eq','User Right') | list }}"
  loop_control:
    label: "{{ item.value.name }}"

# Apply all security registry keys relating to server role
- name: "Apply Registry Keys"
  win_regedit:
    path: "{{ item.value.properties.path }}"
    name: "{{ item.value.properties.name }}"
    data: "{{ item.value.properties.data }}"
    type: "{{ item.value.properties.type }}"
  when:
    - item.value.enabled
    - server_role == item.value.role
  tags: item.value.tags
  loop: "{{ r2019 | dict2items | selectattr('value.module','eq','registry') | list }}"
  loop_control:
    label: "{{ item.value.name }}"