---
- debug:
    msg: |
      {{ r2019 | dict2items }}


- name: "Manage System Access"
  debug:
    msg: Testing loop {{ item }}
  loop: "{{ r2019 | dict2items | selectattr('value.section','eq','System Access') | list }}"
