---

- name: "ensure all template files are rendered"
  win_security_policy:
    section: "{{ item.1.section }}"
    key: "{{ item.1.key }}"
    value: "{{ item.1.value }}"
  # Define a 'list of hashes' for the loop module to iterate over
  # Each item has a 'src' and a 'dest'
  loop: "{{ r2019 }}"
  loop_control:
    index_var: my_idx
