---
- debug:
    msg: |
      {{ r2019 | dict2items }}


- name: "Manage System Access"
  win_security_policy:
    section: System Access
  loop: "{{ r2019 | dict2items | selectattr('value.section','eq','System Access') | list }}"
