---

- debug:
    msg: |
      {{ r2019 | dict2items }}


- win_security_policy:
    section: 'System Access'
    key: "{{ item.value.properties.key }}"
    value: "{{ item.value.properties.value }}"
  when: "{{ item.value.enabled }}"
  loop: "{{ r2019 | dict2items | selectattr('value.section','eq','System Access') | list }}"
  name: "{{ item.value.name }}"