---

- debug:
    msg: |
      {{ r2019 | dict2items }}


- name: "Testing loop"
  win_security_policy:
    section: 'System Access'
    key: "{{ item[1]key }}"
    value: "{{ item[1]value }}"
  when: "{{ item[0]enabled.value }}"
  loop: "{{ r2019 | dict2items | selectattr('value.section','eq','System Access') | list }}"

- name: "Apply User Rights"
  debug:
    msg: Testing loop {{ item }}
  loop: "{{ r2019 | dict2items | selectattr('value.section','eq','User Right') | list }}"